import FormalScience

set_option pp.universes true
set_option pp.explicit true

#check @FormalScience.Stage0.QubitMatrix
#check @FormalScience.Stage0.IsDensity
#check @FormalScience.Stage0.basisProjector
#check @FormalScience.Stage0.basisProjector_eq_single
#check @FormalScience.Stage0.basisProjector_isDensity
#check @FormalScience.Stage0.diagonalState
#check @FormalScience.Stage0.diagonalState_isDensity
#check @FormalScience.Stage0.diagonalState_zero
#check @FormalScience.Stage0.diagonalState_one
#check @FormalScience.Stage0.basisProjector_zero_ne_one
#check @FormalScience.Stage0.krausMap
#check @FormalScience.Stage0.krausMap_trace
#check @FormalScience.Stage0.krausMap_trace_preserving
#check @FormalScience.Stage0.identityKraus_complete
#check @FormalScience.Stage0.identityKraus_apply
#check @FormalScience.OpenSystems.dissipator
#check @FormalScience.OpenSystems.dissipator_add
#check @FormalScience.OpenSystems.dissipator_smul
#check @FormalScience.OpenSystems.dissipatorLinearMap
#check @FormalScience.OpenSystems.dissipatorLinearMap_apply
#check @FormalScience.OpenSystems.dissipator_trace
#check @FormalScience.OpenSystems.isHermitian_anticommutator
#check @FormalScience.OpenSystems.isSelfAdjoint_half
#check @FormalScience.OpenSystems.dissipator_isHermitian
#check @FormalScience.OpenSystems.jumpZeroToOne
#check @FormalScience.OpenSystems.jumpOneToZero
#check @FormalScience.OpenSystems.jumpZeroToOne_conjTranspose
#check @FormalScience.OpenSystems.jumpOneToZero_conjTranspose
#check @FormalScience.OpenSystems.jumpZeroToOne_conjTranspose_mul_self
#check @FormalScience.OpenSystems.jumpOneToZero_conjTranspose_mul_self
#check @FormalScience.OpenSystems.jumpZeroToOne_mul_mul_conjTranspose
#check @FormalScience.OpenSystems.jumpOneToZero_mul_mul_conjTranspose
#check @FormalScience.OpenSystems.dissipator_jumpZeroToOne_eq
#check @FormalScience.OpenSystems.dissipator_jumpOneToZero_eq
#check @FormalScience.OpenSystems.dissipator_jumpZeroToOne_trace
#check @FormalScience.OpenSystems.dissipator_jumpOneToZero_trace
#check @FormalScience.OpenSystems.dissipator_jumpZeroToOne_isHermitian
#check @FormalScience.OpenSystems.dissipator_jumpOneToZero_isHermitian
#check @FormalScience.OpenSystems.jumpZeroToOne_not_isHermitian
#check @FormalScience.OpenSystems.jumpOneToZero_not_isHermitian
#check @FormalScience.OpenSystems.dissipator_jumpZeroToOne_basisProjector_zero
#check @FormalScience.OpenSystems.dissipator_jumpOneToZero_basisProjector_one
#check @FormalScience.OpenSystems.isSelfAdjoint_ofReal
#check @FormalScience.OpenSystems.qubitMatrix_ext
#check @FormalScience.OpenSystems.generator
#check @FormalScience.OpenSystems.generator_apply
#check @FormalScience.OpenSystems.generator_apply_zero_zero
#check @FormalScience.OpenSystems.generator_apply_one_one
#check @FormalScience.OpenSystems.generator_apply_zero_one
#check @FormalScience.OpenSystems.generator_apply_one_zero
#check @FormalScience.OpenSystems.generator_trace
#check @FormalScience.OpenSystems.generator_isHermitian
#check @FormalScience.OpenSystems.rhoStar
#check @FormalScience.OpenSystems.rhoStar_eq_diagonal
#check @FormalScience.OpenSystems.rhoStar_apply_zero_zero
#check @FormalScience.OpenSystems.rhoStar_apply_one_one
#check @FormalScience.OpenSystems.rhoStar_apply_zero_one
#check @FormalScience.OpenSystems.rhoStar_apply_one_zero
#check @FormalScience.OpenSystems.generator_rhoStar
#check @FormalScience.OpenSystems.generator_eq_zero_iff_of_trace_eq_one
#check @FormalScience.OpenSystems.rhoStar_isDensity
#check @FormalScience.OpenSystems.isDensity_generator_eq_zero_iff
#check @FormalScience.OpenSystems.existsUnique_stationary_density
#check @FormalScience.OpenSystems.rhoStar_zero_left
#check @FormalScience.OpenSystems.isDensity_generator_zero_left_eq_zero_iff
#check @FormalScience.OpenSystems.rhoStar_zero_right
#check @FormalScience.OpenSystems.isDensity_generator_zero_right_eq_zero_iff
#check @FormalScience.OpenSystems.generator_zero_zero
#check @FormalScience.OpenSystems.generator_zero_zero_of_isDensity
#check @FormalScience.OpenSystems.not_existsUnique_stationary_density_zero_zero
#check @FormalScience.OpenSystems.rhoStar_same
#check @FormalScience.OpenSystems.isDensity_generator_same_eq_zero_iff
#check @FormalScience.OpenSystems.expFactor
#check @FormalScience.OpenSystems.halfExpFactor
#check @FormalScience.OpenSystems.integratedExpFactor
#check @FormalScience.OpenSystems.expFactor_zero
#check @FormalScience.OpenSystems.halfExpFactor_zero
#check @FormalScience.OpenSystems.integratedExpFactor_zero
#check @FormalScience.OpenSystems.integratedExpFactor_of_eq_zero
#check @FormalScience.OpenSystems.integratedExpFactor_of_ne_zero
#check @FormalScience.OpenSystems.halfExpFactor_of_eq_zero
#check @FormalScience.OpenSystems.expFactor_of_eq_zero
#check @FormalScience.OpenSystems.mul_integratedExpFactor
#check @FormalScience.OpenSystems.integratedExpFactor_add
#check @FormalScience.OpenSystems.halfExpFactor_add
#check @FormalScience.OpenSystems.hasDerivAt_expFactor
#check @FormalScience.OpenSystems.hasDerivAt_halfExpFactor
#check @FormalScience.OpenSystems.hasDerivAt_integratedExpFactor
#check @FormalScience.OpenSystems.evolution
#check @FormalScience.OpenSystems.evolution_apply_diag
#check @FormalScience.OpenSystems.evolution_apply_offDiag
#check @FormalScience.OpenSystems.evolution_apply_zero_zero
#check @FormalScience.OpenSystems.evolution_apply_one_one
#check @FormalScience.OpenSystems.evolution_apply_zero_one
#check @FormalScience.OpenSystems.evolution_apply_one_zero
#check @FormalScience.OpenSystems.evolution_zero
#check @FormalScience.OpenSystems.evolution_add
#check @FormalScience.OpenSystems.evolution_trace
#check @FormalScience.OpenSystems.qubitMatrix_isHermitian_of_entries
#check @FormalScience.OpenSystems.evolution_isHermitian
#check @FormalScience.OpenSystems.hasDerivAt_qubitMatrix
#check @FormalScience.OpenSystems.hasDerivAt_evolution
#check @FormalScience.OpenSystems.evolution_apply_of_generator_eq_zero
#check @FormalScience.OpenSystems.evolution_rhoStar
#check @FormalScience.OpenSystems.evolution_apply_zero_zero_of_ne_zero
#check @FormalScience.OpenSystems.evolution_apply_one_one_of_ne_zero
#check @FormalScience.OpenSystems.evolution_eq_id_add_smul_generator
#check @FormalScience.OpenSystems.evolution_zero_zero
#check @FormalScience.OpenSystems.evolution_one_neg_one_basisProjector_zero
#check @FormalScience.OpenSystems.generator_zero_left_basisProjector_zero
#check @FormalScience.OpenSystems.generator_zero_right_basisProjector_one
#check @FormalScience.OpenSystems.generator_same_diagonalState_half
#check @FormalScience.OpenSystems.evolution_zero_left_basisProjector_zero
#check @FormalScience.OpenSystems.evolution_zero_right_basisProjector_one
#check @FormalScience.OpenSystems.evolution_same_diagonalState_half
#check @FormalScience.Quantum.krausMap_posSemidef
#check @FormalScience.Quantum.amplify
#check @FormalScience.Quantum.amplify_apply
#check @FormalScience.Quantum.amplify_krausMap
#check @FormalScience.Quantum.amplify_krausMap_posSemidef
#check @FormalScience.Quantum.amplify_kronecker
#check @FormalScience.OpenSystems.equilibriumZero
#check @FormalScience.OpenSystems.jumpAmplitude
#check @FormalScience.OpenSystems.halfExpFactor_sq
#check @FormalScience.OpenSystems.halfExpFactor_pos
#check @FormalScience.OpenSystems.halfExpFactor_le_one
#check @FormalScience.OpenSystems.one_sub_halfExpFactor_sq_nonneg
#check @FormalScience.OpenSystems.jumpAmplitude_sq
#check @FormalScience.OpenSystems.equilibriumZero_nonneg
#check @FormalScience.OpenSystems.equilibriumZero_le_one
#check @FormalScience.OpenSystems.one_sub_equilibriumZero
#check @FormalScience.OpenSystems.equilibriumZero_of_add_eq_zero
#check @FormalScience.OpenSystems.eq_zero_of_add_eq_zero
#check @FormalScience.OpenSystems.evolutionKraus
#check @FormalScience.OpenSystems.evolutionKraus_apply_zero
#check @FormalScience.OpenSystems.evolutionKraus_apply_one
#check @FormalScience.OpenSystems.evolutionKraus_apply_two
#check @FormalScience.OpenSystems.evolutionKraus_apply_three
#check @FormalScience.OpenSystems.evolutionKraus_complete
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_apply_zero_zero
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_apply_one_one
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_apply_zero_one
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_apply_one_zero
#check @FormalScience.OpenSystems.evolution_eq_krausMap
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_trace
#check @FormalScience.OpenSystems.evolution_posSemidef
#check @FormalScience.OpenSystems.evolution_isDensity
#check @FormalScience.OpenSystems.amplify_evolution_eq_krausMap
#check @FormalScience.OpenSystems.amplify_evolution_posSemidef
#check @FormalScience.OpenSystems.amplify_evolution_kronecker
#check @FormalScience.OpenSystems.evolutionKraus_zero_zero
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_zero_zero
#check @FormalScience.OpenSystems.evolutionKraus_time_zero
#check @FormalScience.OpenSystems.krausMap_evolutionKraus_time_zero
#check @FormalScience.OpenSystems.evolutionKraus_zero_left
#check @FormalScience.OpenSystems.evolutionKraus_zero_right
#check @FormalScience.OpenSystems.evolution_isDensity_zero_left
#check @FormalScience.OpenSystems.evolution_isDensity_zero_right
#check @FormalScience.OpenSystems.qubitFrobeniusNorm
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_def
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_eq_norm
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_nonneg
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_sq
#check @FormalScience.OpenSystems.expFactor_pos
#check @FormalScience.OpenSystems.expFactor_tendsto
#check @FormalScience.OpenSystems.halfExpFactor_tendsto
#check @FormalScience.OpenSystems.evolution_sub_smul_rhoStar_apply_zero_zero
#check @FormalScience.OpenSystems.evolution_sub_smul_rhoStar_apply_one_one
#check @FormalScience.OpenSystems.evolution_sub_smul_rhoStar_apply_zero_one
#check @FormalScience.OpenSystems.evolution_sub_smul_rhoStar_apply_one_zero
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_sq_evolution_sub
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_evolution_sub_le
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_evolution_sub_rhoStar_le
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_evolution_sub_evolution_le
#check @FormalScience.OpenSystems.tendsto_qubitFrobeniusNorm_evolution_sub
#check @FormalScience.OpenSystems.tendsto_qubitMatrix
#check @FormalScience.OpenSystems.tendsto_evolution
#check @FormalScience.OpenSystems.tendsto_evolution_of_trace_eq_one
#check @FormalScience.OpenSystems.evolution_isDensity_and_qubitFrobeniusNorm_le
#check @FormalScience.OpenSystems.tendsto_evolution_of_isDensity
#check @FormalScience.OpenSystems.tendsto_evolution_zero_left
#check @FormalScience.OpenSystems.tendsto_evolution_zero_right
#check @FormalScience.OpenSystems.tendsto_evolution_same
#check @FormalScience.OpenSystems.not_exists_common_limit_zero_zero
#check @FormalScience.OpenSystems.evolution_jumpOneToZero
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_jumpOneToZero
#check @FormalScience.OpenSystems.qubitFrobeniusNorm_evolution_jumpOneToZero
#check @FormalScience.OpenSystems.exitRate
#check @FormalScience.OpenSystems.exitRate_def
#check @FormalScience.OpenSystems.rateMatrix
#check @FormalScience.OpenSystems.rateMatrix_apply_of_ne
#check @FormalScience.OpenSystems.rateMatrix_apply_diag
#check @FormalScience.OpenSystems.rateMatrix_sum_col
#check @FormalScience.OpenSystems.rateMatrix_mulVec_apply
#check @FormalScience.OpenSystems.sum_rateMatrix_mulVec
#check @FormalScience.OpenSystems.exitRate_nonneg
#check @FormalScience.OpenSystems.rateMatrix_nonneg_of_ne
#check @FormalScience.OpenSystems.dissipator_single
#check @FormalScience.OpenSystems.markovGenerator
#check @FormalScience.OpenSystems.markovGenerator_apply
#check @FormalScience.OpenSystems.markovGenerator_apply_diag
#check @FormalScience.OpenSystems.markovGenerator_apply_of_ne
#check @FormalScience.OpenSystems.markovGenerator_trace
#check @FormalScience.OpenSystems.markovGenerator_isHermitian
#check @FormalScience.OpenSystems.markovGenerator_diagonal
#check @FormalScience.OpenSystems.markovGenerator_diagonal_eq_zero_iff
#check @FormalScience.OpenSystems.diagonal_ofReal_posSemidef_trace_one
#check @FormalScience.OpenSystems.stationary_diagonal_density
#check @FormalScience.OpenSystems.exitRate_zero
#check @FormalScience.OpenSystems.rateMatrix_zero
#check @FormalScience.OpenSystems.markovGenerator_zero
#check @FormalScience.OpenSystems.exitRate_diagonal
#check @FormalScience.OpenSystems.rateMatrix_diagonal
#check @FormalScience.OpenSystems.markovGenerator_diagonal_rates
#check @FormalScience.OpenSystems.rateMatrix_two
#check @FormalScience.OpenSystems.markovGenerator_two
